[package]
name = "bellhop-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bellhop"
path = "src/main.rs"

[dependencies]
bellhop = { path = "../bellhop" }
clap = { version = "4.5.41", features = ["derive"] }

[lints]
workspace = true
