[package]
name = "bellhop-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bellhop"
path = "src/main.rs"

[dependencies]
bellhop = { path = "../bellhop" }
bellhop-hdf5 = { path = "../bellhop-hdf5" }
clap = { version = "4.5.41", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }

[lints]
workspace = true
