[package]
name = "bellhop-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bellhop"
path = "src/main.rs"

[dependencies]
bellhop = { path = "../bellhop" }
hdf5 = { package = "hdf5-metno", version = "0.14.1", features = ["static"] }
sha2 = "0.10.9"
clap = { version = "4.5.41", features = ["derive"] }

[lints]
workspace = true
