[package]
name = "bellhop-hdf5"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bellhop = { path = "../bellhop" }
hdf5 = { package = "hdf5-metno", version = "0.14.1", features = ["static"] }
sha2 = "0.10.9"

[lints]
workspace = true
